/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class PasswordHackerTest {

    PasswordHacker passwordHacker = new PasswordHacker("$2a$10$XEaF37eD5O4aLMtD30s1ouJencvNY3hPb1T5cPYzhmwwIYfLRwq0u", 3);

    @Test
    public void crackPassword() {
        assertThat(passwordHacker.loopThroughPossibilities()).isEqualTo("/3e");
    }


}

